### ISSUE TITLE
'as-user' not found

### ISSUE THREAD

**Issue by AJenbo** [mkenney/docker-phpunit#1]
commit 2c7ded7f8a282bcef77bf088b556dd7eb03f4ab2 has introduced a breaking change:
Status: Downloaded newer image for mkenney/phpunit:latest
ERROR: Container command 'as-user' not found or does not exist.

**Comment by mkenney** [comment]
Hi AJ, sorry, I didn't get notified when you posted. I fixed that, you should be good to go in both branches.
